In [213]:
import pandas as pd
import numpy as np
from xgboost import XGBRegressor

In [214]:
df = pd.read_csv('1H.csv')
df.drop(columns='Unnamed: 0', inplace=True)
df = df.loc[~(df['last open10'].isnull())]
df

,last open10,last high10,last low10,last open9,last high9,last low9,last open8,last high8,last low8,last open7,...,last open1,last high1,last low1,last open,last high,last low,<OPEN>,<HIGH>,<LOW>,<CLOSE>
11,1.34320,1.34330,1.34250,1.34280,1.34280,1.34230,1.34220,1.34240,1.34160,1.34170,...,1.34360,1.34390,1.34190,1.34370,1.34380,1.34320,1.34340,1.34340,1.34270,1.34280
12,1.34280,1.34280,1.34230,1.34220,1.34240,1.34160,1.34170,1.34270,1.34110,1.34260,...,1.34370,1.34380,1.34320,1.34340,1.34340,1.34270,1.34290,1.34430,1.34280,1.34340
13,1.34220,1.34240,1.34160,1.34170,1.34270,1.34110,1.34260,1.34270,1.34210,1.34240,...,1.34340,1.34340,1.34270,1.34290,1.34430,1.34280,1.34330,1.34410,1.34320,1.34350
14,1.34170,1.34270,1.34110,1.34260,1.34270,1.34210,1.34240,1.34250,1.34190,1.34220,...,1.34290,1.34430,1.34280,1.34330,1.34410,1.34320,1.34360,1.34560,1.34360,1.34550
15,1.34260,1.34270,1.34210,1.34240,1.34250,1.34190,1.34220,1.34220,1.34130,1.34190,...,1.34330,1.34410,1.34320,1.34360,1.34560,1.34360,1.34540,1.34570,1.34460,1.34460
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1.12413,1.12413,1.12328,1.12332,1.12353,1.12183,1.12193,1.12257,1.12056,1.12101,...,1.12258,1.12441,1.12177,1.12344,1.12444,1.12150,1.12418,1.12444,1.12350,1.12357
99996,1.12332,1.12353,1.12183,1.12193,1.12257,1.12056,1.12101,1.12217,1.12043,1.12215,...,1.12344,1.12444,1.12150,1.12418,1.12444,1.12350,1.12357,1.12432,1.12331,1.12395
99997,1.12193,1.12257,1.12056,1.12101,1.12217,1.12043,1.12215,1.12358,1.12213,1.12313,...,1.12418,1.12444,1.12350,1.12357,1.12432,1.12331,1.12399,1.12399,1.12265,1.12342
99998,1.12101,1.12217,1.12043,1.12215,1.12358,1.12213,1.12313,1.12450,1.12263,1.12268,...,1.12357,1.12432,1.12331,1.12399,1.12399,1.12265,1.12342,1.12367,1.12314,1.12341
99999,1.12215,1.12358,1.12213,1.12313,1.12450,1.12263,1.12268,1.12268,1.12157,1.12204,...,1.12399,1.12399,1.12265,1.12342,1.12367,1.12314,1.12342,1.12342,1.12302,1.12303

In [215]:
x = df.drop(columns=['<HIGH>', '<LOW>', '<CLOSE>'])
y = df['<HIGH>']
x

,last open10,last high10,last low10,last open9,last high9,last low9,last open8,last high8,last low8,last open7,...,last open2,last high2,last low2,last open1,last high1,last low1,last open,last high,last low,<OPEN>
11,1.34320,1.34330,1.34250,1.34280,1.34280,1.34230,1.34220,1.34240,1.34160,1.34170,...,1.34230,1.34380,1.34210,1.34360,1.34390,1.34190,1.34370,1.34380,1.34320,1.34340
12,1.34280,1.34280,1.34230,1.34220,1.34240,1.34160,1.34170,1.34270,1.34110,1.34260,...,1.34360,1.34390,1.34190,1.34370,1.34380,1.34320,1.34340,1.34340,1.34270,1.34290
13,1.34220,1.34240,1.34160,1.34170,1.34270,1.34110,1.34260,1.34270,1.34210,1.34240,...,1.34370,1.34380,1.34320,1.34340,1.34340,1.34270,1.34290,1.34430,1.34280,1.34330
14,1.34170,1.34270,1.34110,1.34260,1.34270,1.34210,1.34240,1.34250,1.34190,1.34220,...,1.34340,1.34340,1.34270,1.34290,1.34430,1.34280,1.34330,1.34410,1.34320,1.34360
15,1.34260,1.34270,1.34210,1.34240,1.34250,1.34190,1.34220,1.34220,1.34130,1.34190,...,1.34290,1.34430,1.34280,1.34330,1.34410,1.34320,1.34360,1.34560,1.34360,1.34540
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1.12413,1.12413,1.12328,1.12332,1.12353,1.12183,1.12193,1.12257,1.12056,1.12101,...,1.12244,1.12272,1.12099,1.12258,1.12441,1.12177,1.12344,1.12444,1.12150,1.12418
99996,1.12332,1.12353,1.12183,1.12193,1.12257,1.12056,1.12101,1.12217,1.12043,1.12215,...,1.12258,1.12441,1.12177,1.12344,1.12444,1.12150,1.12418,1.12444,1.12350,1.12357
99997,1.12193,1.12257,1.12056,1.12101,1.12217,1.12043,1.12215,1.12358,1.12213,1.12313,...,1.12344,1.12444,1.12150,1.12418,1.12444,1.12350,1.12357,1.12432,1.12331,1.12399
99998,1.12101,1.12217,1.12043,1.12215,1.12358,1.12213,1.12313,1.12450,1.12263,1.12268,...,1.12418,1.12444,1.12350,1.12357,1.12432,1.12331,1.12399,1.12399,1.12265,1.12342
99999,1.12215,1.12358,1.12213,1.12313,1.12450,1.12263,1.12268,1.12268,1.12157,1.12204,...,1.12357,1.12432,1.12331,1.12399,1.12399,1.12265,1.12342,1.12367,1.12314,1.12342

In [216]:
regressorHigh = XGBRegressor(tree_method='hist', n_estimators=2000)
regressorHigh.fit(x.values, y.values)
predHigh = np.around(regressorHigh.predict(x.values), 4)
predHigh

array([1.3433, 1.3433, 1.3433, ..., 1.1245, 1.1243, 1.1243], dtype=float32)

In [217]:
x = df.drop(columns=['<LOW>', '<CLOSE>'])
y = df['<LOW>']
x

,last open10,last high10,last low10,last open9,last high9,last low9,last open8,last high8,last low8,last open7,...,last high2,last low2,last open1,last high1,last low1,last open,last high,last low,<OPEN>,<HIGH>
11,1.34320,1.34330,1.34250,1.34280,1.34280,1.34230,1.34220,1.34240,1.34160,1.34170,...,1.34380,1.34210,1.34360,1.34390,1.34190,1.34370,1.34380,1.34320,1.34340,1.34340
12,1.34280,1.34280,1.34230,1.34220,1.34240,1.34160,1.34170,1.34270,1.34110,1.34260,...,1.34390,1.34190,1.34370,1.34380,1.34320,1.34340,1.34340,1.34270,1.34290,1.34430
13,1.34220,1.34240,1.34160,1.34170,1.34270,1.34110,1.34260,1.34270,1.34210,1.34240,...,1.34380,1.34320,1.34340,1.34340,1.34270,1.34290,1.34430,1.34280,1.34330,1.34410
14,1.34170,1.34270,1.34110,1.34260,1.34270,1.34210,1.34240,1.34250,1.34190,1.34220,...,1.34340,1.34270,1.34290,1.34430,1.34280,1.34330,1.34410,1.34320,1.34360,1.34560
15,1.34260,1.34270,1.34210,1.34240,1.34250,1.34190,1.34220,1.34220,1.34130,1.34190,...,1.34430,1.34280,1.34330,1.34410,1.34320,1.34360,1.34560,1.34360,1.34540,1.34570
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1.12413,1.12413,1.12328,1.12332,1.12353,1.12183,1.12193,1.12257,1.12056,1.12101,...,1.12272,1.12099,1.12258,1.12441,1.12177,1.12344,1.12444,1.12150,1.12418,1.12444
99996,1.12332,1.12353,1.12183,1.12193,1.12257,1.12056,1.12101,1.12217,1.12043,1.12215,...,1.12441,1.12177,1.12344,1.12444,1.12150,1.12418,1.12444,1.12350,1.12357,1.12432
99997,1.12193,1.12257,1.12056,1.12101,1.12217,1.12043,1.12215,1.12358,1.12213,1.12313,...,1.12444,1.12150,1.12418,1.12444,1.12350,1.12357,1.12432,1.12331,1.12399,1.12399
99998,1.12101,1.12217,1.12043,1.12215,1.12358,1.12213,1.12313,1.12450,1.12263,1.12268,...,1.12444,1.12350,1.12357,1.12432,1.12331,1.12399,1.12399,1.12265,1.12342,1.12367
99999,1.12215,1.12358,1.12213,1.12313,1.12450,1.12263,1.12268,1.12268,1.12157,1.12204,...,1.12432,1.12331,1.12399,1.12399,1.12265,1.12342,1.12367,1.12314,1.12342,1.12342

In [218]:
regressorLow = XGBRegressor(tree_method='hist', n_estimators=2000)
regressorLow.fit(x.values, y.values)
predLow = np.around(regressorLow.predict(x.values), 4)

In [219]:
predLow

array([1.3424, 1.3424, 1.3424, ..., 1.1231, 1.1228, 1.1228], dtype=float32)

In [220]:
x = df.drop(columns=['<CLOSE>'])
y = df['<CLOSE>']
x

,last open10,last high10,last low10,last open9,last high9,last low9,last open8,last high8,last low8,last open7,...,last low2,last open1,last high1,last low1,last open,last high,last low,<OPEN>,<HIGH>,<LOW>
11,1.34320,1.34330,1.34250,1.34280,1.34280,1.34230,1.34220,1.34240,1.34160,1.34170,...,1.34210,1.34360,1.34390,1.34190,1.34370,1.34380,1.34320,1.34340,1.34340,1.34270
12,1.34280,1.34280,1.34230,1.34220,1.34240,1.34160,1.34170,1.34270,1.34110,1.34260,...,1.34190,1.34370,1.34380,1.34320,1.34340,1.34340,1.34270,1.34290,1.34430,1.34280
13,1.34220,1.34240,1.34160,1.34170,1.34270,1.34110,1.34260,1.34270,1.34210,1.34240,...,1.34320,1.34340,1.34340,1.34270,1.34290,1.34430,1.34280,1.34330,1.34410,1.34320
14,1.34170,1.34270,1.34110,1.34260,1.34270,1.34210,1.34240,1.34250,1.34190,1.34220,...,1.34270,1.34290,1.34430,1.34280,1.34330,1.34410,1.34320,1.34360,1.34560,1.34360
15,1.34260,1.34270,1.34210,1.34240,1.34250,1.34190,1.34220,1.34220,1.34130,1.34190,...,1.34280,1.34330,1.34410,1.34320,1.34360,1.34560,1.34360,1.34540,1.34570,1.34460
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1.12413,1.12413,1.12328,1.12332,1.12353,1.12183,1.12193,1.12257,1.12056,1.12101,...,1.12099,1.12258,1.12441,1.12177,1.12344,1.12444,1.12150,1.12418,1.12444,1.12350
99996,1.12332,1.12353,1.12183,1.12193,1.12257,1.12056,1.12101,1.12217,1.12043,1.12215,...,1.12177,1.12344,1.12444,1.12150,1.12418,1.12444,1.12350,1.12357,1.12432,1.12331
99997,1.12193,1.12257,1.12056,1.12101,1.12217,1.12043,1.12215,1.12358,1.12213,1.12313,...,1.12150,1.12418,1.12444,1.12350,1.12357,1.12432,1.12331,1.12399,1.12399,1.12265
99998,1.12101,1.12217,1.12043,1.12215,1.12358,1.12213,1.12313,1.12450,1.12263,1.12268,...,1.12350,1.12357,1.12432,1.12331,1.12399,1.12399,1.12265,1.12342,1.12367,1.12314
99999,1.12215,1.12358,1.12213,1.12313,1.12450,1.12263,1.12268,1.12268,1.12157,1.12204,...,1.12331,1.12399,1.12399,1.12265,1.12342,1.12367,1.12314,1.12342,1.12342,1.12302

In [221]:
regressorClose = XGBRegressor(tree_method='hist', n_estimators=2000)
regressorClose.fit(x.values, y.values)
predClose = np.around(regressorClose.predict(x.values), 4)
predClose

array([1.3434, 1.3433, 1.3433, ..., 1.1233, 1.1236, 1.1234], dtype=float32)

In [222]:
df['<CLOSE>']

11       1.34280
12       1.34340
13       1.34350
14       1.34550
15       1.34460
          ...
99995    1.12357
99996    1.12395
99997    1.12342
99998    1.12341
99999    1.12303
Name: <CLOSE>, Length: 99989, dtype: float64

In [223]:
testSet = pd.read_csv('test.csv')
testSet

,Unnamed: 0,last open10,last high10,last low10,last open9,last high9,last low9,last open8,last high8,last low8,...,last open1,last high1,last low1,last open,last high,last low,<OPEN>,<HIGH>,<LOW>,<CLOSE>
0,100000,1.12313,1.12450,1.12263,1.12268,1.12268,1.12157,1.12204,1.12343,1.12194,...,1.12342,1.12367,1.12314,1.12342,1.12342,1.12302,1.12288,1.12345,1.12195,1.12289
1,100001,1.12268,1.12268,1.12157,1.12204,1.12343,1.12194,1.12244,1.12272,1.12099,...,1.12342,1.12342,1.12302,1.12288,1.12345,1.12195,1.12293,1.12314,1.12240,1.12250
2,100002,1.12204,1.12343,1.12194,1.12244,1.12272,1.12099,1.12258,1.12441,1.12177,...,1.12288,1.12345,1.12195,1.12293,1.12314,1.12240,1.12250,1.12293,1.12229,1.12269
3,100003,1.12244,1.12272,1.12099,1.12258,1.12441,1.12177,1.12344,1.12444,1.12150,...,1.12293,1.12314,1.12240,1.12250,1.12293,1.12229,1.12273,1.12297,1.12232,1.12246
4,100004,1.12258,1.12441,1.12177,1.12344,1.12444,1.12150,1.12418,1.12444,1.12350,...,1.12250,1.12293,1.12229,1.12273,1.12297,1.12232,1.12246,1.12273,1.12171,1.12177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,100115,1.11396,1.11438,1.11338,1.11432,1.11449,1.11355,1.11430,1.11447,1.11250,...,1.11187,1.11188,1.11080,1.11132,1.11261,1.11122,1.11197,1.11254,1.11156,1.11235
116,100116,1.11432,1.11449,1.11355,1.11430,1.11447,1.11250,1.11280,1.11377,1.11216,...,1.11132,1.11261,1.11122,1.11197,1.11254,1.11156,1.11235,1.11290,1.11229,1.11260
117,100117,1.11430,1.11447,1.11250,1.11280,1.11377,1.11216,1.11283,1.11321,1.11220,...,1.11197,1.11254,1.11156,1.11235,1.11290,1.11229,1.11260,1.11303,1.11241,1.11248
118,100118,1.11280,1.11377,1.11216,1.11283,1.11321,1.11220,1.11280,1.11292,1.11202,...,1.11235,1.11290,1.11229,1.11260,1.11303,1.11241,1.11248,1.11255,1.11192,1.11255
119,100119,1.11283,1.11321,1.11220,1.11280,1.11292,1.11202,1.11255,1.11314,1.11173,...,1.11260,1.11303,1.11241,1.11248,1.11255,1.11192,1.11254,1.11292,1.11241,1.11246

In [224]:
testSet.drop(columns='Unnamed: 0', inplace=True)
testSet

,last open10,last high10,last low10,last open9,last high9,last low9,last open8,last high8,last low8,last open7,...,last open1,last high1,last low1,last open,last high,last low,<OPEN>,<HIGH>,<LOW>,<CLOSE>
0,1.12313,1.12450,1.12263,1.12268,1.12268,1.12157,1.12204,1.12343,1.12194,1.12244,...,1.12342,1.12367,1.12314,1.12342,1.12342,1.12302,1.12288,1.12345,1.12195,1.12289
1,1.12268,1.12268,1.12157,1.12204,1.12343,1.12194,1.12244,1.12272,1.12099,1.12258,...,1.12342,1.12342,1.12302,1.12288,1.12345,1.12195,1.12293,1.12314,1.12240,1.12250
2,1.12204,1.12343,1.12194,1.12244,1.12272,1.12099,1.12258,1.12441,1.12177,1.12344,...,1.12288,1.12345,1.12195,1.12293,1.12314,1.12240,1.12250,1.12293,1.12229,1.12269
3,1.12244,1.12272,1.12099,1.12258,1.12441,1.12177,1.12344,1.12444,1.12150,1.12418,...,1.12293,1.12314,1.12240,1.12250,1.12293,1.12229,1.12273,1.12297,1.12232,1.12246
4,1.12258,1.12441,1.12177,1.12344,1.12444,1.12150,1.12418,1.12444,1.12350,1.12357,...,1.12250,1.12293,1.12229,1.12273,1.12297,1.12232,1.12246,1.12273,1.12171,1.12177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,1.11396,1.11438,1.11338,1.11432,1.11449,1.11355,1.11430,1.11447,1.11250,1.11280,...,1.11187,1.11188,1.11080,1.11132,1.11261,1.11122,1.11197,1.11254,1.11156,1.11235
116,1.11432,1.11449,1.11355,1.11430,1.11447,1.11250,1.11280,1.11377,1.11216,1.11283,...,1.11132,1.11261,1.11122,1.11197,1.11254,1.11156,1.11235,1.11290,1.11229,1.11260
117,1.11430,1.11447,1.11250,1.11280,1.11377,1.11216,1.11283,1.11321,1.11220,1.11280,...,1.11197,1.11254,1.11156,1.11235,1.11290,1.11229,1.11260,1.11303,1.11241,1.11248
118,1.11280,1.11377,1.11216,1.11283,1.11321,1.11220,1.11280,1.11292,1.11202,1.11255,...,1.11235,1.11290,1.11229,1.11260,1.11303,1.11241,1.11248,1.11255,1.11192,1.11255
119,1.11283,1.11321,1.11220,1.11280,1.11292,1.11202,1.11255,1.11314,1.11173,1.11184,...,1.11260,1.11303,1.11241,1.11248,1.11255,1.11192,1.11254,1.11292,1.11241,1.11246

In [225]:
testDF = pd.DataFrame()

In [226]:
testDF['Open'] = testSet['<OPEN>']
testDF['Real Close'] = testSet['<CLOSE>']
testDF

        Open  Real Close
0    1.12288     1.12289
1    1.12293     1.12250
2    1.12250     1.12269
3    1.12273     1.12246
4    1.12246     1.12177
..       ...         ...
115  1.11197     1.11235
116  1.11235     1.11260
117  1.11260     1.11248
118  1.11248     1.11255
119  1.11254     1.11246

[120 rows x 2 columns]

In [227]:
xx = testSet.iloc[:, :34]
xx['predHigh'] = np.around(regressorHigh.predict(xx.values), 5)
xx

C:\Users\Farbod\AppData\Local\Temp\ipykernel_6444\2616564042.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xx['predHigh'] = np.around(regressorHigh.predict(xx.values), 5)

,last open10,last high10,last low10,last open9,last high9,last low9,last open8,last high8,last low8,last open7,...,last high2,last low2,last open1,last high1,last low1,last open,last high,last low,<OPEN>,predHigh
0,1.12313,1.12450,1.12263,1.12268,1.12268,1.12157,1.12204,1.12343,1.12194,1.12244,...,1.12399,1.12265,1.12342,1.12367,1.12314,1.12342,1.12342,1.12302,1.12288,1.12410
1,1.12268,1.12268,1.12157,1.12204,1.12343,1.12194,1.12244,1.12272,1.12099,1.12258,...,1.12367,1.12314,1.12342,1.12342,1.12302,1.12288,1.12345,1.12195,1.12293,1.12410
2,1.12204,1.12343,1.12194,1.12244,1.12272,1.12099,1.12258,1.12441,1.12177,1.12344,...,1.12342,1.12302,1.12288,1.12345,1.12195,1.12293,1.12314,1.12240,1.12250,1.12287
3,1.12244,1.12272,1.12099,1.12258,1.12441,1.12177,1.12344,1.12444,1.12150,1.12418,...,1.12345,1.12195,1.12293,1.12314,1.12240,1.12250,1.12293,1.12229,1.12273,1.12287
4,1.12258,1.12441,1.12177,1.12344,1.12444,1.12150,1.12418,1.12444,1.12350,1.12357,...,1.12314,1.12240,1.12250,1.12293,1.12229,1.12273,1.12297,1.12232,1.12246,1.12287
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,1.11396,1.11438,1.11338,1.11432,1.11449,1.11355,1.11430,1.11447,1.11250,1.11280,...,1.11381,1.11117,1.11187,1.11188,1.11080,1.11132,1.11261,1.11122,1.11197,1.11209
116,1.11432,1.11449,1.11355,1.11430,1.11447,1.11250,1.11280,1.11377,1.11216,1.11283,...,1.11188,1.11080,1.11132,1.11261,1.11122,1.11197,1.11254,1.11156,1.11235,1.11323
117,1.11430,1.11447,1.11250,1.11280,1.11377,1.11216,1.11283,1.11321,1.11220,1.11280,...,1.11261,1.11122,1.11197,1.11254,1.11156,1.11235,1.11290,1.11229,1.11260,1.11363
118,1.11280,1.11377,1.11216,1.11283,1.11321,1.11220,1.11280,1.11292,1.11202,1.11255,...,1.11254,1.11156,1.11235,1.11290,1.11229,1.11260,1.11303,1.11241,1.11248,1.11363
119,1.11283,1.11321,1.11220,1.11280,1.11292,1.11202,1.11255,1.11314,1.11173,1.11184,...,1.11290,1.11229,1.11260,1.11303,1.11241,1.11248,1.11255,1.11192,1.11254,1.11323

In [228]:
xx['predLow'] = np.around(regressorLow.predict(xx.values), 5)
xx

C:\Users\Farbod\AppData\Local\Temp\ipykernel_6444\1495289415.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  xx['predLow'] = np.around(regressorLow.predict(xx.values), 5)

,last open10,last high10,last low10,last open9,last high9,last low9,last open8,last high8,last low8,last open7,...,last low2,last open1,last high1,last low1,last open,last high,last low,<OPEN>,predHigh,predLow
0,1.12313,1.12450,1.12263,1.12268,1.12268,1.12157,1.12204,1.12343,1.12194,1.12244,...,1.12265,1.12342,1.12367,1.12314,1.12342,1.12342,1.12302,1.12288,1.12410,1.12294
1,1.12268,1.12268,1.12157,1.12204,1.12343,1.12194,1.12244,1.12272,1.12099,1.12258,...,1.12314,1.12342,1.12342,1.12302,1.12288,1.12345,1.12195,1.12293,1.12410,1.12259
2,1.12204,1.12343,1.12194,1.12244,1.12272,1.12099,1.12258,1.12441,1.12177,1.12344,...,1.12302,1.12288,1.12345,1.12195,1.12293,1.12314,1.12240,1.12250,1.12287,1.12182
3,1.12244,1.12272,1.12099,1.12258,1.12441,1.12177,1.12344,1.12444,1.12150,1.12418,...,1.12195,1.12293,1.12314,1.12240,1.12250,1.12293,1.12229,1.12273,1.12287,1.12186
4,1.12258,1.12441,1.12177,1.12344,1.12444,1.12150,1.12418,1.12444,1.12350,1.12357,...,1.12240,1.12250,1.12293,1.12229,1.12273,1.12297,1.12232,1.12246,1.12287,1.12186
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,1.11396,1.11438,1.11338,1.11432,1.11449,1.11355,1.11430,1.11447,1.11250,1.11280,...,1.11117,1.11187,1.11188,1.11080,1.11132,1.11261,1.11122,1.11197,1.11209,1.11045
116,1.11432,1.11449,1.11355,1.11430,1.11447,1.11250,1.11280,1.11377,1.11216,1.11283,...,1.11080,1.11132,1.11261,1.11122,1.11197,1.11254,1.11156,1.11235,1.11323,1.11198
117,1.11430,1.11447,1.11250,1.11280,1.11377,1.11216,1.11283,1.11321,1.11220,1.11280,...,1.11122,1.11197,1.11254,1.11156,1.11235,1.11290,1.11229,1.11260,1.11363,1.11218
118,1.11280,1.11377,1.11216,1.11283,1.11321,1.11220,1.11280,1.11292,1.11202,1.11255,...,1.11156,1.11235,1.11290,1.11229,1.11260,1.11303,1.11241,1.11248,1.11363,1.11254
119,1.11283,1.11321,1.11220,1.11280,1.11292,1.11202,1.11255,1.11314,1.11173,1.11184,...,1.11229,1.11260,1.11303,1.11241,1.11248,1.11255,1.11192,1.11254,1.11323,1.11218

In [229]:
xx['predClose'] = np.around(regressorClose.predict(xx.values), 5)
xx

,last open10,last high10,last low10,last open9,last high9,last low9,last open8,last high8,last low8,last open7,...,last open1,last high1,last low1,last open,last high,last low,<OPEN>,predHigh,predLow,predClose
0,1.12313,1.12450,1.12263,1.12268,1.12268,1.12157,1.12204,1.12343,1.12194,1.12244,...,1.12342,1.12367,1.12314,1.12342,1.12342,1.12302,1.12288,1.12410,1.12294,1.12356
1,1.12268,1.12268,1.12157,1.12204,1.12343,1.12194,1.12244,1.12272,1.12099,1.12258,...,1.12342,1.12342,1.12302,1.12288,1.12345,1.12195,1.12293,1.12410,1.12259,1.12334
2,1.12204,1.12343,1.12194,1.12244,1.12272,1.12099,1.12258,1.12441,1.12177,1.12344,...,1.12288,1.12345,1.12195,1.12293,1.12314,1.12240,1.12250,1.12287,1.12182,1.12215
3,1.12244,1.12272,1.12099,1.12258,1.12441,1.12177,1.12344,1.12444,1.12150,1.12418,...,1.12293,1.12314,1.12240,1.12250,1.12293,1.12229,1.12273,1.12287,1.12186,1.12215
4,1.12258,1.12441,1.12177,1.12344,1.12444,1.12150,1.12418,1.12444,1.12350,1.12357,...,1.12250,1.12293,1.12229,1.12273,1.12297,1.12232,1.12246,1.12287,1.12186,1.12215
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,1.11396,1.11438,1.11338,1.11432,1.11449,1.11355,1.11430,1.11447,1.11250,1.11280,...,1.11187,1.11188,1.11080,1.11132,1.11261,1.11122,1.11197,1.11209,1.11045,1.11146
116,1.11432,1.11449,1.11355,1.11430,1.11447,1.11250,1.11280,1.11377,1.11216,1.11283,...,1.11132,1.11261,1.11122,1.11197,1.11254,1.11156,1.11235,1.11323,1.11198,1.11277
117,1.11430,1.11447,1.11250,1.11280,1.11377,1.11216,1.11283,1.11321,1.11220,1.11280,...,1.11197,1.11254,1.11156,1.11235,1.11290,1.11229,1.11260,1.11363,1.11218,1.11277
118,1.11280,1.11377,1.11216,1.11283,1.11321,1.11220,1.11280,1.11292,1.11202,1.11255,...,1.11235,1.11290,1.11229,1.11260,1.11303,1.11241,1.11248,1.11363,1.11254,1.11312
119,1.11283,1.11321,1.11220,1.11280,1.11292,1.11202,1.11255,1.11314,1.11173,1.11184,...,1.11260,1.11303,1.11241,1.11248,1.11255,1.11192,1.11254,1.11323,1.11218,1.11277

In [230]:
testDF['predClose'] = xx['predClose']
testDF['Real Close - Open'] = testDF['Real Close'] - testDF['Open']
testDF['predClose - Open'] = testDF['predClose'] - testDF['Open']
testDF['product'] = testDF['Real Close - Open'] * testDF['predClose - Open']
testDF

,Open,Real Close,predClose,Real Close - Open,predClose - Open,product
0,1.12288,1.12289,1.12356,0.00001,0.00068,6.799518e-09
1,1.12293,1.12250,1.12334,-0.00043,0.00041,-1.763046e-07
2,1.12250,1.12269,1.12215,0.00019,-0.00035,-6.651058e-08
3,1.12273,1.12246,1.12215,-0.00027,-0.00058,1.566150e-07
4,1.12246,1.12177,1.12215,-0.00069,-0.00031,2.139384e-07
...,...,...,...,...,...,...
115,1.11197,1.11235,1.11146,0.00038,-0.00051,-1.938112e-07
116,1.11235,1.11260,1.11277,0.00025,0.00042,1.049903e-07
117,1.11260,1.11248,1.11277,-0.00012,0.00017,-2.039536e-08
118,1.11248,1.11255,1.11312,0.00007,0.00064,4.479719e-08
119,1.11254,1.11246,1.11277,-0.00008,0.00023,-1.839691e-08

In [231]:
testDF.shape[0]

120

In [232]:
len(testDF.loc[testDF['product'] > 0]) / testDF.shape[0] * 100

51.66666666666667